


# 指数行情
index_feed_channel: 'tcp://192.168.211.194:7778'
# 快照行情
tick_feed_channel: 'tcp://192.168.211.194:7779'
# 逐笔成交
trade_feed_channel: 'tcp://192.168.211.194:7781'
# 逐笔报单
order_feed_channel: 'tcp://192.168.211.194:7782'
# 交易队列
queue_feed_channel: 'tcp://192.168.211.194:7783'
# 期权行情
options_feed_channel: 'tcp://192.168.211.194:7784'
# ctp期货行情
ctp_feed_channel: 'tcp://192.168.221.82:9504'


# 同步请求
sync_channel_port: 'tcp://192.168.221.37:9833'
# 异步请求
async_channel_port: 'tcp://192.168.221.37:9831'
# 柜台推送
rsp_channel_port: 'tcp://192.168.221.67:12432'
# 风控消息
risk_channel_port: 'tcp://192.168.221.36:9402'


# 终端信息
mac: '02:15:51:37:6C:14'
harddisk: 'W62H0HQL'
ip: '192.168.211.201'


# rest api
use_rest_api: True

rest_api:
  # kay_file: 'c:/Users/{user}/AppData/Roaming/Kay/.kay'
  kay_file: '/home/jovyan/work/fast-trader/tmp/kay.txt'
  get_account: 'https://192.168.221.39:444/api/entrust-free/accounts'
  order: 'https://192.168.221.39:444/api/entrust-free/accounts/{account_no}/orders'
  cancel_order: 'https://192.168.221.39:444/api/entrust-free/accounts/{account_no}/order_cancellations'
  batch_order: 'https://192.168.221.39:444/api/entrust-free/accounts/{account_no}/batchOrder'
  cancel_batch: 'https://192.168.221.39:444/api/entrust-free/accounts/{account_no}/batchCancel'
  
  query_capital: 'https://192.168.221.39:444/api/counter-cache/query/capitals/{account_no}'
  query_positions: 'https://192.168.221.39:444/api/counter-cache/query/positions/{account_no}'
  query_fills: 'https://192.168.221.39:444/api/counter-cache/query/fills/{account_no}'
  query_orders: 'https://192.168.221.39:444/api/counter-cache/query/orders/{account_no}'
  query_open_orders: 'https://192.168.221.39:444/api/counter-cache/query/cancelableorders/{account_no}'


working_dir: ''

sqlalchemy_url: 'sqlite:///{fast_trader_home}/fast_trader.db'
sqlite_ledger: '{fast_trader_home}/ledger.db'
sqlite_market_quote: '{fast_trader_home}/market_quote.db'

strategy_mananger_host: '127.0.0.1'
strategy_mananger_port: 5600
strategy_directory: '{fast_trader_home}/strategies'


# 账号
account: '011000106328'
# 密码
password: '111111'


# 内部order_id分配逻辑参数
_IDPool:
  # 最多可分配的策略
  max_strategies: 100
  # 每个策略最多可对应的trader数量
  max_traders_per_strategy: 2


logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: "%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s"
        debug:
            format: "%(asctime)s - %(process)d - %(threadName)s - %(name)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s"
        user:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            level: WARNING
            formatter: simple
            stream: ext://sys.stdout
    
        info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: debug
            filename: '{fast_trader_home}/logs/info.{today_str}.log'
            maxBytes: 1048576 # 1MB
            backupCount: 20
            encoding: utf8
    
        error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: '{fast_trader_home}/logs/error.{today_str}.log'
            maxBytes: 1048576 # 1MB
            backupCount: 20
            encoding: utf8
        
        user_log_handler:
            class: logging.FileHandler
            level: INFO
            formatter: user
            filename: '{fast_trader_home}/logs/strategy.{today_str}.log'
            encoding: utf8
    
    loggers:

        dispathcer:
            level: DEBUG
            handlers: [info_file_handler, error_file_handler, console]
            propagate: no

        dtp:
            level: DEBUG
            handlers: [info_file_handler, error_file_handler, console]
            propagate: no
            
        trader:
            level: DEBUG
            handlers: [info_file_handler, error_file_handler, console]
            propagate: no

        strategy:
            level: INFO
            handlers: [user_log_handler]
            propagate: no
        
        strategy_manager:
            level: INFO
            handlers: [info_file_handler, error_file_handler]
            propagate: no
        
        strategy_server:
            level: INFO
            handlers: [info_file_handler, error_file_handler, console]
            propagate: no
        
        settings:
            level: INFO
            handlers: [info_file_handler, error_file_handler, console]
            propagate: no

        rest_api:
            level: INFO
            handlers: [info_file_handler, error_file_handler]
            propagate: no
    
    root:
        level: DEBUG
        handlers: [user_log_handler]

