

# 指数行情
index_feed_channel: 'tcp://192.168.211.194:7778'
# 快照行情
tick_feed_channel: 'tcp://192.168.211.194:7779'
# 逐笔成交
trade_feed_channel: 'tcp://192.168.211.194:7781'
# 逐笔报单
order_feed_channel: 'tcp://192.168.211.194:7782'
# 交易队列
queue_feed_channel: 'tcp://192.168.211.194:7783'
# 期权行情
options_feed_channel: 'tcp://192.168.211.194:7784'
# ctp期货行情
ctp_feed_channel: 'tcp://192.168.221.82:9504'


# 同步请求
sync_channel_port: 'tcp://192.168.221.37:9833'
# 异步请求
async_channel_port: 'tcp://192.168.221.37:9831'
# 异步响应推送
rsp_channel_port: 'tcp://192.168.221.37:9832'
# 风控消息
risk_channel_port: 'tcp://192.168.221.36:9402'


# rest api
use_rest_api: True

rest_api:
  kay_file: 'c:/Users/{user}/AppData/Roaming/Kay/.kay'
#  get_account: 'http://192.168.221.36:8101/accounts'
#  order: 'http://192.168.221.36:8101/accounts/{account_no}/orders'
#  cancel_order: 'http://192.168.221.36:8101/accounts/{account_no}/order_cancellations'
#  batch_order: 'http://192.168.221.36:8101/accounts/{account_no}/batchOrder'
#  cancel_batch: 'http://192.168.221.36:8101/accounts/{account_no}/batchCancel'
  get_account: 'https://192.168.221.39/api/entrust-free/accounts'
  order: 'https://192.168.221.39/api/entrust-free/accounts/{account_no}/orders'
  cancel_order: 'https://192.168.221.39/api/entrust-free/accounts/{account_no}/order_cancellations'
  batch_order: 'https://192.168.221.39/api/entrust-free/accounts/{account_no}/batchOrder'
  cancel_batch: 'https://192.168.221.39/api/entrust-free/accounts/{account_no}/batchCancel'
  
  query_capital: 'https://192.168.221.39/api/counter-cache/query/capitals/{account_no}'
  query_positions: 'https://192.168.221.39/api/counter-cache/query/positions/{account_no}'
  query_fills: 'https://192.168.221.39/api/counter-cache/query/fills/{account_no}'
  query_orders: 'https://192.168.221.39/api/counter-cache/query/orders/{account_no}'
  query_open_orders: 'https://192.168.221.39/api/counter-cache/query/cancelableorders/{account_no}'


## rest api
#use_rest_api: True
#
#rest_api:
#  kay_file: 'c:/dataUpdate/fast-trader/fast_trader/tmp.kay'
##  get_account: 'https://112.80.54.190:40443/accounts'
##  order: 'http://192.168.221.36:8101/accounts/{account_no}/orders'
##  cancel_order: 'http://192.168.221.36:8101/accounts/{account_no}/order_cancellations'
##  batch_order: 'http://192.168.221.36:8101/accounts/{account_no}/batchOrder'
##  cancel_batch: 'http://192.168.221.36:8101/accounts/{account_no}/batchCancel'
#  get_account: 'https://112.80.54.190:40443/api/entrust-free/accounts'
#  order: 'https://112.80.54.190:40443/api/entrust-free/accounts/{account_no}/orders'
#  cancel_order: 'https://112.80.54.190:40443/api/entrust-free/accounts/{account_no}/order_cancellations'
#  batch_order: 'https://112.80.54.190:40443/api/entrust-free/accounts/{account_no}/batchOrder'
#  cancel_batch: 'https://112.80.54.190:40443/api/entrust-free/accounts/{account_no}/batchCancel'
#  
#  query_capital: 'https://112.80.54.190:40443/api/counter-cache/query/capitals/{account_no}'
#  query_positions: 'https://112.80.54.190:40443/api/counter-cache/query/positions/{account_no}'
#  query_fills: 'https://112.80.54.190:40443/api/counter-cache/query/fills/{account_no}'
#  query_orders: 'https://112.80.54.190:40443/api/counter-cache/query/orders/{account_no}'
#  query_open_orders: 'https://112.80.54.190:40443/api/counter-cache/query/cancelableorders/{account_no}'


working_dir: ''
app:
  # sqlalchemy_url: 'mysql+pymysql://root:idwzx.com@192.168.211.190:3306/dtp_trade_test?charset=utf8'
  # sqlalchemy_url: 'sqlite:////dataUpdate/fast-trader/tmp/test_sqlite.db'
  sqlalchemy_url: 'sqlite:///{fast_trader_home}/fast_trader.db'
  strategy_host: '127.0.0.1'
  strategy_port: 5600
  # strategy_directory: '/Users/eisenheim/Documents/git/fast-trader/fast_trader/app'
  strategy_directory: '{fast_trader_home}/strategies'


quote_feed_store:
  disk_store_folder: '~/work/share/cache'
  compress: False


# 账号
account: '011000106328'
# 密码
password: '111111'


logging:
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: "%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s"
        debug:
            format: "%(asctime)s - %(threadName)s - %(name)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s"
    
    handlers:
        console:
            class: logging.StreamHandler
            level: WARNING
            formatter: simple
            stream: ext://sys.stdout
    
        info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: debug
            filename: info.log
            maxBytes: 1048576 # 1MB
            backupCount: 20
            encoding: utf8
    
        error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: errors.log
            maxBytes: 1048576 # 1MB
            backupCount: 20
            encoding: utf8
    
    loggers:
        my_module:
            level: ERROR
            handlers: [console]
            propagate: no
    
    root:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
