# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtp.type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtp.type.proto',
  package='dwjk.dtp',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64tp.type.proto\x12\x08\x64wjk.dtp*\xd1\x01\n\x12ResponseStatusCode\x12\"\n\x1eRESPONSE_STATUS_CODE_UNDEFINED\x10\x00\x12\x15\n\x10RESPONSE_CODE_OK\x10\xc8\x01\x12\x1e\n\x19RESPONSE_CODE_BAD_REQUEST\x10\x90\x03\x12\x1f\n\x1aRESPONSE_CODE_UNAUTHORIZED\x10\x91\x03\x12\x1c\n\x17RESPONSE_CODE_FORBIDDEN\x10\x93\x03\x12!\n\x1cRESPONSE_CODE_INTERNAL_ERROR\x10\xf4\x03*H\n\x08\x45xchange\x12\x16\n\x12\x45XCHANGE_UNDEFINED\x10\x00\x12\x11\n\rEXCHANGE_SH_A\x10\x01\x12\x11\n\rEXCHANGE_SZ_A\x10\x02*;\n\tOrderType\x12\x18\n\x14ORDER_TYPE_UNDEFINED\x10\x00\x12\x14\n\x10ORDER_TYPE_LIMIT\x10\x01*\x9e\x01\n\tOrderSide\x12\x18\n\x14ORDER_SIDE_UNDEFINED\x10\x00\x12\x12\n\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n\x0fORDER_SIDE_SELL\x10\x02\x12\x17\n\x13ORDER_SIDE_CREATION\x10\x0b\x12\x18\n\x14ORDER_SIDE_REDEMPTON\x10\x0c\x12\x1b\n\x17ORDER_SIDE_REVERSE_REPO\x10\x15*\xb1\x02\n\x0bOrderStatus\x12\x1a\n\x16ORDER_STATUS_UNDEFINED\x10\x00\x12\x18\n\x14ORDER_STATUS_PLACING\x10\x01\x12\x17\n\x13ORDER_STATUS_PLACED\x10\x02\x12\x1f\n\x1bORDER_STATUS_PARTIAL_FILLED\x10\x03\x12\x17\n\x13ORDER_STATUS_FILLED\x10\x04\x12\x1b\n\x17ORDER_STATUS_CANCELLING\x10\x05\x12\x1a\n\x16ORDER_STATUS_CANCELLED\x10\x06\x12#\n\x1fORDER_STATUS_PARTIAL_CANCELLING\x10\x07\x12\"\n\x1eORDER_STATUS_PARTIAL_CANCELLED\x10\x08\x12\x17\n\x13ORDER_STATUS_FAILED\x10\t*r\n\nFillStatus\x12\x19\n\x15\x46ILL_STATUS_UNDEFINED\x10\x00\x12\x16\n\x12\x46ILL_STATUS_FILLED\x10\x01\x12\x19\n\x15\x46ILL_STATUS_CANCELLED\x10\x02\x12\x16\n\x12\x46ILL_STATUS_FAILED\x10\x03*~\n\x12QueryOrderCriteria\x12\x14\n\x10QUERY_ONLY_ORDER\x10\x00\x12 \n\x1cQUERY_ORDER_CAN_BE_CANCELLED\x10\x01\x12\x1b\n\x17QUERY_ONLY_CANCEL_ORDER\x10\x02\x12\x13\n\x0fQUERY_ORDER_ALL\x10\x03\x62\x06proto3')
)

_RESPONSESTATUSCODE = _descriptor.EnumDescriptor(
  name='ResponseStatusCode',
  full_name='dwjk.dtp.ResponseStatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESPONSE_STATUS_CODE_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE_CODE_OK', index=1, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE_CODE_BAD_REQUEST', index=2, number=400,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE_CODE_UNAUTHORIZED', index=3, number=401,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE_CODE_FORBIDDEN', index=4, number=403,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE_CODE_INTERNAL_ERROR', index=5, number=500,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=29,
  serialized_end=238,
)
_sym_db.RegisterEnumDescriptor(_RESPONSESTATUSCODE)

ResponseStatusCode = enum_type_wrapper.EnumTypeWrapper(_RESPONSESTATUSCODE)
_EXCHANGE = _descriptor.EnumDescriptor(
  name='Exchange',
  full_name='dwjk.dtp.Exchange',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXCHANGE_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCHANGE_SH_A', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCHANGE_SZ_A', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=240,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_EXCHANGE)

Exchange = enum_type_wrapper.EnumTypeWrapper(_EXCHANGE)
_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='dwjk.dtp.OrderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORDER_TYPE_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_TYPE_LIMIT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=314,
  serialized_end=373,
)
_sym_db.RegisterEnumDescriptor(_ORDERTYPE)

OrderType = enum_type_wrapper.EnumTypeWrapper(_ORDERTYPE)
_ORDERSIDE = _descriptor.EnumDescriptor(
  name='OrderSide',
  full_name='dwjk.dtp.OrderSide',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORDER_SIDE_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_SIDE_BUY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_SIDE_SELL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_SIDE_CREATION', index=3, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_SIDE_REDEMPTON', index=4, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_SIDE_REVERSE_REPO', index=5, number=21,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=376,
  serialized_end=534,
)
_sym_db.RegisterEnumDescriptor(_ORDERSIDE)

OrderSide = enum_type_wrapper.EnumTypeWrapper(_ORDERSIDE)
_ORDERSTATUS = _descriptor.EnumDescriptor(
  name='OrderStatus',
  full_name='dwjk.dtp.OrderStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_PLACING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_PLACED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_PARTIAL_FILLED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_FILLED', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_CANCELLING', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_CANCELLED', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_PARTIAL_CANCELLING', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_PARTIAL_CANCELLED', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_STATUS_FAILED', index=9, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=537,
  serialized_end=842,
)
_sym_db.RegisterEnumDescriptor(_ORDERSTATUS)

OrderStatus = enum_type_wrapper.EnumTypeWrapper(_ORDERSTATUS)
_FILLSTATUS = _descriptor.EnumDescriptor(
  name='FillStatus',
  full_name='dwjk.dtp.FillStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FILL_STATUS_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILL_STATUS_FILLED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILL_STATUS_CANCELLED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILL_STATUS_FAILED', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=844,
  serialized_end=958,
)
_sym_db.RegisterEnumDescriptor(_FILLSTATUS)

FillStatus = enum_type_wrapper.EnumTypeWrapper(_FILLSTATUS)
_QUERYORDERCRITERIA = _descriptor.EnumDescriptor(
  name='QueryOrderCriteria',
  full_name='dwjk.dtp.QueryOrderCriteria',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUERY_ONLY_ORDER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY_ORDER_CAN_BE_CANCELLED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY_ONLY_CANCEL_ORDER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY_ORDER_ALL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=960,
  serialized_end=1086,
)
_sym_db.RegisterEnumDescriptor(_QUERYORDERCRITERIA)

QueryOrderCriteria = enum_type_wrapper.EnumTypeWrapper(_QUERYORDERCRITERIA)
RESPONSE_STATUS_CODE_UNDEFINED = 0
RESPONSE_CODE_OK = 200
RESPONSE_CODE_BAD_REQUEST = 400
RESPONSE_CODE_UNAUTHORIZED = 401
RESPONSE_CODE_FORBIDDEN = 403
RESPONSE_CODE_INTERNAL_ERROR = 500
EXCHANGE_UNDEFINED = 0
EXCHANGE_SH_A = 1
EXCHANGE_SZ_A = 2
ORDER_TYPE_UNDEFINED = 0
ORDER_TYPE_LIMIT = 1
ORDER_SIDE_UNDEFINED = 0
ORDER_SIDE_BUY = 1
ORDER_SIDE_SELL = 2
ORDER_SIDE_CREATION = 11
ORDER_SIDE_REDEMPTON = 12
ORDER_SIDE_REVERSE_REPO = 21
ORDER_STATUS_UNDEFINED = 0
ORDER_STATUS_PLACING = 1
ORDER_STATUS_PLACED = 2
ORDER_STATUS_PARTIAL_FILLED = 3
ORDER_STATUS_FILLED = 4
ORDER_STATUS_CANCELLING = 5
ORDER_STATUS_CANCELLED = 6
ORDER_STATUS_PARTIAL_CANCELLING = 7
ORDER_STATUS_PARTIAL_CANCELLED = 8
ORDER_STATUS_FAILED = 9
FILL_STATUS_UNDEFINED = 0
FILL_STATUS_FILLED = 1
FILL_STATUS_CANCELLED = 2
FILL_STATUS_FAILED = 3
QUERY_ONLY_ORDER = 0
QUERY_ORDER_CAN_BE_CANCELLED = 1
QUERY_ONLY_CANCEL_ORDER = 2
QUERY_ORDER_ALL = 3


DESCRIPTOR.enum_types_by_name['ResponseStatusCode'] = _RESPONSESTATUSCODE
DESCRIPTOR.enum_types_by_name['Exchange'] = _EXCHANGE
DESCRIPTOR.enum_types_by_name['OrderType'] = _ORDERTYPE
DESCRIPTOR.enum_types_by_name['OrderSide'] = _ORDERSIDE
DESCRIPTOR.enum_types_by_name['OrderStatus'] = _ORDERSTATUS
DESCRIPTOR.enum_types_by_name['FillStatus'] = _FILLSTATUS
DESCRIPTOR.enum_types_by_name['QueryOrderCriteria'] = _QUERYORDERCRITERIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
